version: '3.8'

services:
  game-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Optional: mount a volume for logs
      - ./logs:/app/logs
