name: secrets

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check .env is not committed
        run: |
          if git ls-files --error-unmatch .env; then
            echo ".env file is committed! Please remove it from the repository."
            exit 1
          else
            echo ".env file is not committed. Good!"
          fi
