name: Unit Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a placeholder for unit tests."